-- Esquema MARQUEZA (MariaDB/MySQL).
-- Inferido de backend/API/Services/*.py (INSERT/UPDATE) y Models/*.py.
-- Solo el módulo `productos` está verificado end-to-end; el resto es
-- base para replicar la plantilla. Sin FKs a propósito: el repo no las define.
-- Uso:  mariadb -u root < schema.sql   (o mysql)

CREATE DATABASE IF NOT EXISTS marqueza
  DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci;
USE marqueza;

CREATE TABLE IF NOT EXISTS T_PERSONA (
  PER_ID INT AUTO_INCREMENT PRIMARY KEY,
  PER_UUID VARCHAR(64),
  PER_NOMBRE VARCHAR(100) NOT NULL,
  PER_SEG_NOMBRE VARCHAR(100) NULL,
  PER_PRI_APELLIDO VARCHAR(100) NOT NULL,
  PER_SEG_APELLIDO VARCHAR(100) NULL,
  PER_CORREO VARCHAR(150) NULL,
  PER_DIRECCION VARCHAR(200) NULL,
  PER_IDENTIFICACION VARCHAR(50) NULL,
  PER_TELEFONO VARCHAR(50) NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS T_ESTADO_TIPOS_CATEGORIAS (
  ETC_ID INT AUTO_INCREMENT PRIMARY KEY,
  ETC_UUID VARCHAR(64),
  ETC_NOMBRE VARCHAR(100) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS T_DETALLES_ETC (
  DET_ETC_ID INT AUTO_INCREMENT PRIMARY KEY,
  DET_ETC_UUID VARCHAR(64),
  DET_ETC_NOMBRE VARCHAR(100) NOT NULL,
  DET_ETC_ETC_ID INT NULL,
  DET_ETC_PER_ID INT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS T_USUARIOS (
  USUA_ID INT AUTO_INCREMENT PRIMARY KEY,
  USUA_UUID VARCHAR(64),
  USUA_NOMBRE VARCHAR(100) NOT NULL,
  USUA_CORREO VARCHAR(150) NOT NULL,
  USUA_CONTRASENA VARCHAR(255) NOT NULL,
  USUA_ESTADO VARCHAR(20) DEFAULT 'activo',
  USUA_DET_ETC_ID INT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS T_CLIENTE (
  CLI_ID INT AUTO_INCREMENT PRIMARY KEY,
  CLI_UUID VARCHAR(64),
  CLI_PER_ID INT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS T_PROVEEDORES (
  PROV_ID INT AUTO_INCREMENT PRIMARY KEY,
  PROV_UUID VARCHAR(64),
  PROV_PER_ID INT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS T_CONTACTO (
  CONT_ID INT AUTO_INCREMENT PRIMARY KEY,
  CONT_UUID VARCHAR(64),
  CONT_TIPO_DATO VARCHAR(50) NULL,
  CONT_CONTENIDO VARCHAR(255) NULL,
  CONT_PROV_ID INT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS T_PRODUCTOS (
  PROD_ID INT AUTO_INCREMENT PRIMARY KEY,
  PROD_UUID VARCHAR(64),
  PROD_CODIGO VARCHAR(50) NOT NULL,
  PROD_NOMBRE VARCHAR(100) NOT NULL,
  PROD_CANTIDAD INT NOT NULL DEFAULT 0,
  PROD_PRECIO DECIMAL(12,2) NOT NULL DEFAULT 0,
  PROD_ESTADO VARCHAR(20) DEFAULT 'activo',
  PROD_USUA_ID INT NULL,
  PROD_DET_ETC_ID INT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS T_INSUMOS (
  INS_ID INT AUTO_INCREMENT PRIMARY KEY,
  INS_UUID VARCHAR(64),
  INS_CODIGO VARCHAR(50) NOT NULL,
  INS_NOMBRE VARCHAR(100) NOT NULL,
  INS_CANTIDAD INT NOT NULL DEFAULT 0,
  INS_PRECIO DECIMAL(12,2) NOT NULL DEFAULT 0,
  INS_ESTADO VARCHAR(20) DEFAULT 'activo',
  INS_USUA_ID INT NULL,
  INS_PROV_ID INT NULL,
  INS_DET_ETC_ID INT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS T_PRODU_INSUM (
  PROINSU_ID INT AUTO_INCREMENT PRIMARY KEY,
  PROINSU_UUID VARCHAR(64),
  PROINSU_CANTIDAD INT NOT NULL DEFAULT 0,
  PROINSU_PROD_ID INT NULL,
  PROINSU_INS_ID INT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS T_COTIZACIONES (
  COT_ID INT AUTO_INCREMENT PRIMARY KEY,
  COT_UUID VARCHAR(64),
  COT_PRO_CODIGO VARCHAR(50) NULL,
  COT_PRO_NOMBRE VARCHAR(100) NULL,
  COT_PRO_CANTIDAD INT NOT NULL DEFAULT 0,
  COT_PRO_PRECIO DECIMAL(12,2) NOT NULL DEFAULT 0,
  COT_TOTAL_PAGAR DECIMAL(12,2) NULL,
  COT_USUA_ID INT NULL,
  COT_CLI_ID INT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS T_VENTAS (
  VENT_ID INT AUTO_INCREMENT PRIMARY KEY,
  VENT_UUID VARCHAR(64),
  VENT_FECHA DATETIME DEFAULT CURRENT_TIMESTAMP,
  VENT_PRO_CODIGO VARCHAR(50) NULL,
  VENT_PRO_NOMBRE VARCHAR(100) NULL,
  VENT_USUA_ID INT NULL,
  VENT_CLI_ID INT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS T_VENT_PROD (
  VENTPRO_ID INT AUTO_INCREMENT PRIMARY KEY,
  VENTPRO_UUID VARCHAR(64),
  VENTPRO_CANTIDAD INT NOT NULL DEFAULT 0,
  VENTPRO_VENT_ID INT NULL,
  VENTPRO_PROD_ID INT NULL
) ENGINE=InnoDB;
