ALTER TABLE t_persona
    MODIFY COLUMN PER_IDENTIFICACION BIGINT NOT NULL,
    MODIFY COLUMN PER_TELEFONO BIGINT NOT NULL;

ALTER TABLE t_insumos
    ADD COLUMN INS_UNIDAD VARCHAR(45) NOT NULL DEFAULT 'unidad';

ALTER TABLE t_vent_prod
    ADD COLUMN VENPRO_PRECIO INT NOT NULL DEFAULT 0;

ALTER TABLE t_cotizaciones
    ADD COLUMN COT_FECHA DATE NULL,
    ADD COLUMN COT_ESTADO VARCHAR(20) NOT NULL DEFAULT 'Pendiente',
    ADD COLUMN COT_NOTAS TEXT NULL,
    ADD COLUMN COT_DETALLE_JSON TEXT NULL;

CREATE TABLE IF NOT EXISTS t_auditoria_ui (
    AUD_ID INT NOT NULL AUTO_INCREMENT,
    AUD_UUID CHAR(36) NOT NULL,
    AUD_TIMESTAMP DATETIME NOT NULL,
    AUD_ACTOR VARCHAR(60) NOT NULL,
    AUD_EMAIL VARCHAR(100) NOT NULL DEFAULT '',
    AUD_ROLE VARCHAR(45) NOT NULL DEFAULT '',
    AUD_ACTION VARCHAR(100) NOT NULL,
    AUD_MODULE VARCHAR(80) NOT NULL,
    AUD_ENTITY VARCHAR(160) NOT NULL DEFAULT '',
    AUD_DETAIL TEXT NOT NULL,
    AUD_OUTCOME VARCHAR(20) NOT NULL DEFAULT 'success',
    PRIMARY KEY (AUD_ID),
    UNIQUE KEY AUD_UUID_UNIQUE (AUD_UUID),
    KEY AUD_TIMESTAMP_IDX (AUD_TIMESTAMP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;